require "rake/testtask"
require "rb_sys/extensiontask"

RbSys::ExtensionTask.new("example") do |ext|
  ext.lib_dir = "ext"
end

namespace :doc do
  task default: %i[rustdoc yard]

  desc "Generate Yard documentation"
  task :yard do
    run("bundle exec yard doc --plugin rustdoc -- lib rustdoc.json")
  end

  desc "Generate Rust documentation as JSON"
  task :rustdoc do
    require "fileutils"
    require "json"

    ext_name = "example"
    nightly = "+nightly"
    nightly += "-#{ENV["NIGHTLY_VERSION"]}" if ENV["NIGHTLY_VERSION"]

    run(<<~CMD)
      cargo #{nightly} rustdoc \
        --target-dir tmp \
        -p #{ext_name} \
        -- \
        -Zunstable-options --output-format json --document-private-items
    CMD

    rustdoc_path = "tmp/doc/#{ext_name}.json"
    version = JSON.load_file(rustdoc_path).fetch("format_version")

    FileUtils.mkdir_p("rustdoc")
    run("cp #{rustdoc_path} rustdoc.json")
    run("cp #{rustdoc_path} rustdoc/v#{version}.json")
  end

  def run(cmd)
    system(cmd)
    fail if $? != 0
  end
end

task doc: "doc:default"
task default: "doc:default"
