require "rake/testtask"
require "rb_sys/extensiontask"

RbSys::ExtensionTask.new("example") do |ext|
  ext.lib_dir = "ext"
end

namespace :doc do
  task default: %i[rustdoc yard]

  desc "Generate Yard documentation"
  task :yard do
    run("bundle exec yard doc --plugin rustdoc -- lib rustdoc.json")
  end

  desc "Generate Rust documentation as JSON"
  task :rustdoc do
    target_dir = "tmp"
    ext_name = "example"
    run(<<~CMD)
      cargo +nightly rustdoc \
        --target-dir #{target_dir} \
        -p #{ext_name} \
        -- \
        -Zunstable-options --output-format json --document-private-items
    CMD

    run("cp #{rustdoc_path} rustdoc.json")
  end

  def run(cmd)
    system(cmd)
    fail if $? != 0
  end
end

task doc: "doc:default"
task default: "doc:default"
